#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
  colorscheme = "OceanicNext"
  colorscheme_bg = "dark"
  enable_ycm=1

# 添加自定义主题：https://github.com/mhartington/oceanic-next
[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = 0  
  # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

[options]
# options for layers checkers
  enable_neomake = true
  enable_ale = false
  lint_on_the_fly = false
# option for autoutocomplete
  autocomplete_method = "coc"
# bootstrap configuration
#1 bootstrap_before = "myspacevim#before" 
# bootstrap_after = "myspacevim#after" 
# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"
[[layers]]
  name = 'checkers'
  show_cursor_error = true
# enable = false
[[layers]]
  name = "lang#c"
  clang_executable = "clang"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"
[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp"
  ]
[layers.override_cmd]
  c = ["clangd", "--limit-results=5"]
  cpp = ["clangd", "--limit-results=5"]
[[layers]]
  name = "format"

[[layers]]
    name = "git"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"
